### ISSUE TITLE
Package name conflict

### ISSUE THREAD

**Issue by elvinsophus** [polkascan/py-ed25519-bindings#2]
This package conflicts with [ed25519](https://github.com/warner/python-ed25519) which is a commonly used library.
Please fix it.
Thanks.

**Comment by elvinsophus** [comment]
Would you please consider changing the name of this package (as well as a few others)?
Thanks.

**Comment by arjanz** [comment]
Yes this will be best considering the ambiguous name, I'll rename the package to `ed25519_dalek` in the next major release

**Comment by arjanz** [comment]
Update released to PYPI: https://pypi.org/project/py-ed25519-bindings/1.0.0/
